/*SELECIONAR O BANCO DE DADOS*/
USE SUCOS;

/*VAMOS EXCLUIR A TABELA*/
DROP TABLE tabela_de_vendedores;

/*CRIANDO A TABELA COM AS COLUNAS E O TIPO DE VVALORES QUE VAO SER ATRIBUIDOS*/
CREATE TABLE TABELA_DE_VENDEDORES (MATRICULA VARCHAR(5), NOME VARCHAR(100),
PERCENTUAL_COMISSAO FLOAT, DATA_ADMISSAO DATE, DE_FERIAS BIT);

/*CRIANDO A CHAVE PRIMARIA DENTRO DA TABELA*/
ALTER TABLE TABELA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

/*INSERINDO OS DADOS DENTRO DA TABELA, INFORMANDO OS CAMPOS E OS DADOS*/
INSERT INTO TABELA_DE_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES ('00235', 'Márcio Almeida Silva', '2014-08-15', 0.08,0);

INSERT INTO TABELA_DE_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS) VALUES
('00236', 'Cláudia Morais', '2013-03-18',0.11,1);

INSERT INTO TABELA_DE_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS) VALUES
('00238', 'Pericles Alves', '2016-08-21', 0.11,0);

