USE SUCOS;

ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);

/*ADICIONANDO UMA NOVA COLUNA A TABELA*/
ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO TBCLIENTE (CPF, NOME, ENDERECO1, ENDERECO2,BAIRRO,CIDADE, ESTADO,CEP,IDADE,SEXO,LIMITE_CREDITO, VOLUME_COMPRA,
PRIMEIRA_COMPRA, DATA_NASCIMENTO) VALUES ('00388934505', 'João da Silva', 'Rua projetada numero 10', '','VILA ROMAN', 'CARATINGA', 
'AMAZONAS', '22222222', 30, 'M', 100000.00,20000,0,'1989-10-05');

SELECT DATA_NASCIMENTO FROM TBCLIENTE;

SELECT * FROM TBCLIENTE;