USE SUCOS;
/*DADOS INFORMADOS ERRADOS PARA ALTERAR OS CAMPOS*/
INSERT INTO TBPRODUTO(
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LIST) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LIST) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

/*ALTERANDO OS DADOS*/
/*UPADTE NOME_DA_TABELA SET NOME_DA_COLUNA_NOVOS_VALORES WHERE ESPECIFICANDO_PRODUTO*/
UPDATE TBPRODUTO SET EMBALAGEM = 'LATA' , PRECO_LIST = 2.46 WHERE PRODUTO = '544931';

UPDATE TBPRODUTO SET EMBALAGEM = 'Garrafa' WHERE = '1078680';