USE SUCOS;

SELECT * FROM tbproduto;

/*INCLUINFO UMA CHAVE PRIMARIA DENTRO DE UMA TABELA JÁ EXISTENTE*/
/*ALTERAR A TABELA E ADICIONAR O CAMPO EM ESPECIFICO DA TABELA COMO CHAVE PRIMARIA*/
/*COM UMA CHAVE PRIMARIA EVITA REGISTROS DUPLICADOS DENTRO DA NOSSA TABELA*/
ALTER TABLE tbproduto ADD PRIMARY KEY (PRODUTO);