USE SUCOS;

SELECT *  FROM tbproduto;
/*O COMANDO DROP É PARA APAGAR COMPONENTES, COMO BANCOS, TABELAS, INDICES */

/*COMANDO DELETE SERVE PARA APAGAR DADOS*/
/*COMANDO SIMILAR AO DE ALTERAR DADOS, SEMPRE LEMBRAR DE INFORMAR A CONDICAO*/
DELETE FROM tbproduto WHERE PRODUTO = '1078680';