USE SUCOS;

/*COMANDO PARA INSERIR DADOS NA TABELA */

/*DEVEMOS INFORMAR A TABELA E AS COLUNAS QUE VAMOS INSERIR OS DADOS*/
INSERT INTO TBPRODUTO(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LIST)
/*PARA INFORMAR OS VALORES, DEVO SEGUIR A ORDEM INFORMADA DAS COLUNAS*/
VALUES ('1037797', 'Clean', '2 litros' , 'laranja', 'PET', 10.01);

INSERT INTO TBPRODUTO(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LIST)
/*PARA INFORMAR OS VALORES, DEVO SEGUIR A ORDEM INFORMADA DAS COLUNAS*/
VALUES ('1000889', 'Sabor da montanha', '700 ml' , 'uva', 'Garrafa', 6.31);

INSERT INTO TBPRODUTO(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LIST)
/*PARA INFORMAR OS VALORES, DEVO SEGUIR A ORDEM INFORMADA DAS COLUNAS*/
VALUES ('1004327', 'Videira do Campoe', '1,5 litros' , 'Melancia', 'PET', 19.51);

SELECT* FROM tbproduto;